---
title: "run_model_ocean_case"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(here)
library(quadprog)
```


### Preparing the inputs and outputs for `qb_stock.r`:

For each species, we need:

* r - growth rate
* K - carrying capacity
* X - starting stock
* p - price

For each technology we need:

* Catchability per species
* Cost per unit effort

# Inputs

## Step 1: Input parameters
```{r}
# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.2, K=100, X=50, p=200) 
s2 <- c(s=2, r=0.3, K=100, X=50, p=200)
s3 <- c(s=3, r=0.4, K=100, X=50, p=200) 
s4 <- c(s=4, r=0.5, K=100, X=50, p=200)
s5 <- c(s=5, r=0.6, K=100, X=50, p=200)

# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.05, q2=0.05, q3=0.05, q4=0.05, q5=0.05)
t2 <- c(t=2, q1=0.05, q2=0.05, q3=0.05, q4=0.05, q5=0.05)
t3 <- c(t=3, q1=0.05, q2=0.05, q3=0.05, q4=0.05, q5=0.05)
t4 <- c(t=4, q1=0.05, q2=0.05, q3=0.05, q4=0.05, q5=0.05)
t5 <- c(t=5, q1=0.05, q2=0.05, q3=0.05, q4=0.05, q5=0.05)

# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=10)
c2 <- c(t=2, cost=10)
c3 <- c(t=3, cost=10)
c4 <- c(t=4, cost=10)
c5 <- c(t=5, cost=10)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 1, s3 = 1, s4 = 1, s5 = 1)

# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceeding stock under constant mortality, so this will have to change to just input constant m.

mortality = 0.000000001

# Years
years = 30
```

# Step 2: make a list of the inputs
```{r}
# Change these to reflect the number of species and technologies above:
species = list(s1, s2, s3, s4, s5)
tech = list(t1, t2, t3, t4, t5)
cost = list(c1, c2, c3, c4, c5)
baskets = list(b1)
```

# Step 3: Run the function

```{r}
source(here("working_model", "qb_stock.R"))

output_0 <- qb_stock(species, tech, cost, baskets, mortality, years)

NPV_30_0 <- sum(drop_na(output_0$profit_per_t))

path_store <- "C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/scratch"
  csvname <- "output_0.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(output_0),csvfile, row.names=FALSE, sep=",")
  
path_store <- "C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/scratch"
  csvname <- "NPV_30_0.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(NPV_30_0),csvfile, row.names=FALSE, sep=",")

```
