---
title: "four_basket_optim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ggplot2)
library(here)
library(quadprog)
library(future)
library(ggbeeswarm)
library(gghighlight)
library(kableExtra)
```

### Preparing the inputs and outputs for `qb_stock.r`:

For each species, we need:

* r - growth rate
* K - carrying capacity
* X - starting stock
* p - price

For each technology we need:

* Catchability per species
* Cost per unit effort

# Inputs

## Step 1: Input parameters
```{r}
# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.15, K=100, X=50, p=10) 
s2 <- c(s=2, r=0.2, K=100, X=50, p=20)
s3 <- c(s=3, r=0.2, K=100, X=50, p=8)
s4 <- c(s=4, r=0.3, K=100, X=50, p=10)
s5 <- c(s=5, r=0.4, K=100, X=50, p=12)

# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.04, q2=0.01, q3=0.01, q4=0.01, q5 = 0.1)
t2 <- c(t=2, q1=0.01, q2=0.04, q3=0.01, q4=0.01, q5 = 0.01)
t3 <- c(t=2, q1=0.01, q2=0.01, q3=0.04, q4=0.01, q5 = 0.01)
t4 <- c(t=2, q1=0.01, q2=0.01, q3=0.01, q4=0.04, q5 = 0.01)
t5 <- c(t=2, q1=0.01, q2=0.01, q3=0.01, q4=0.01, q5 = 0.04)

# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=1)
c2 <- c(t=2, cost=1)
c3 <- c(t=3, cost=1)
c4 <- c(t=4, cost=1)
c5 <- c(t=5, cost=1)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

# b1 <- c(s1 = 1, s2 = 0, s3 = 0, s4 = 0, s5 = 0)
# b2 <- c(s1 = 0, s2 = 1, s3 = 0, s4 = 0, s5 = 0)
# b3 <- c(s1 = 0, s2 = 0, s3 = 1, s4 = 0, s5 = 0)
# b4 <- c(s1 = 0, s2 = 0, s3 = 0, s4 = 1, s5 = 0)
# b5 <- c(s1 = 0, s2 = 0, s3 = 0, s4 = 0, s5 = 1)


# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceding stock under constant mortality, so this will have to change to just input constant m.

mort_guess = c(0.2, 0.2, 0.2, 0.2)

# Years
years = 30
```

# Step 2: make a list of the inputs
```{r}
# Change these to reflect the number of species and technologies above:
species = list(s1, s2, s3, s4, s5)
tech = list(t1, t2, t3, t4, t5)
cost = list(c1, c2, c3, c4, c5)
# baskets = list(b1, b2, b3, b4, b5)
```




```{r, eval = FALSE}
# Test run..
source(here("working_model", "functions", "optimal_baskets.R"))
output <- optimal_baskets(species, tech, cost, baskets, mort_guess, years)

# Calculate every basket combo:
matrixCombn <- function(nrow, ncol) {
    # All possible column combinations for a matrix of dimension dim
    # Here we assume two different values c(1, 0)
    require(gtools);
    columns <- t(permutations(n = 2, r = nrow, v = c(1, 0), repeats.allowed = TRUE));
    columns <- columns[, colSums(columns) == 1];

    # Construct all possible combinations of dim column vectors and
    # impose constraint that row and column sum >= 1
    ret <- lapply(as.data.frame(t(permutations(ncol(columns), ncol, repeats.allowed = TRUE))), function(x) {
        m.cand <- columns[, x];
        if (all(rowSums(m.cand) > 0) & all(colSums(m.cand) > 0)) m.cand else NULL;
    })
    ret <- Filter(Negate(is.null), ret);
    return(ret);
}


```

```{r}
every_basket <- function(species, tech, cost, n_baskets, mort_guess, years){
  # Load the two functions
  source(here("working_model", "functions", "qb_stock_m.R"))
  source(here("working_model", "functions", "qb_stock_for_optim.R"))
  source(here("working_model", "functions", "matrix_nodup.R"))

  # Calculate every basket combo: matrix of length 
  bmtx <- matrix_nodup(n_baskets, length(species))
  
  # Make empty vectors:
  profit_end <- NULL
  stock_end <- NULL
  
  basket_fx <- function(basket_list){
    
        # Make the input a list of lists
        baskets <- split(basket_list, 1:nrow(basket_list))
        
        # Optimize over baskets:
        mortality <- optim(par = mort_guess, 
                           qb_stock_for_optim, method = c("L-BFGS-B"), lower = 0.1, 
                           upper = 0.9 ,species = species, tech = tech, cost = cost, baskets = baskets, years = years)
        # Run qb_stock for the optimal mortalities
        result <- c(qb_stock(species = species, tech = tech, 
                             cost = cost, baskets = baskets, mortality = mortality$par, 
                             years = years), mortality = mortality$par)
        # Calculate total profit, bind to vector)
        profit = sum(colSums(result$profit_per_t, na.rm = TRUE))
        end_biomass = as_vector(tail(result$stock, 1))
        return(list(profit, end_biomass))
  }
  plan(multiprocess, workers = 5)
  result <- future.apply::future_lapply(bmtx, possibly(basket_fx, otherwise = NA))

  
  profit <- as_tibble(do.call(rbind, map(result, 1)))
  stock <- as_tibble(do.call(rbind, map(result, 2)))
  return(list(profits = profit, biomass = stock, baskets = bmtx))
}
```

# Run this!
```{r}
output <- every_basket(species, tech, cost, n_baskets = 4, mort_guess, years)

output$profits
output$biomass
output$baskets

biomass <- output$biomass %>% 
  mutate(basket = seq(1, nrow(output$biomass))) %>% 
  pivot_longer(cols = c(s_1, s_2, s_3, s_4, s_5),
               values_to = "biomass",
               names_to = "species")

profits <- output$profits %>% 
  mutate(basket = seq(1, nrow(output$biomass)))
```

# Plot the biomass!

```{r}
ggplot(data = biomass, aes(x = species, y = biomass)) +
  geom_jitter(width = 0.2) +
  theme_bw()
```

# Plot the profits
```{r}
ggplot(data = profits, aes(x = fct_reorder(as.factor(basket), desc(V1)), y = V1, fill = V1)) +
  geom_col() +
  theme_bw() +
  labs (x = "Basket", y = "Profits", title = "Net Profits", fill = "Profits")
```