---
title: "Model methods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Model goals:

We aim to build a fisheries model that allows us to explore how quota baskets affect fisheries stocks. We have broken this approach down into multiple parts:

- Fisheries growth
- Harvest
- Profit

- Adapting the model to include quota baskets:
- Effort allocation
- Yearly optimization


## Underlying fisheries model
### Fisheries growth


To model fisheries growth, we choose a simple von Bertallanffy growth equation as follows:

$X_{t+1} = X_{t} + rX_{t}\times (1-{X_{t}\over K})$

Where the stock *X* at time *t+1* depends on the stock at time *t*, the intrinsic growth rate *r*, and the carrying capacity *K*. A simple growth model makes it easier for us to add complexity to our model in other areas.


### Harvest


Yearly harvest for a species is calculated as follows:

$H = qEX$

where the harvest *H* depends on the stock in the water *X*, the fishing effort *E*, and the catch per unit effort *q*.
With harvest, our yearly stock growth becomes
$X_{t+1} = X_t + growth - harvest$ 
or
$X_{t+1} = X_{t} + rX_{t}\times (1-{X_{t}\over K}) - qEX$

### Cost of fishing

The cost of fishing each year is calculated as follows:

$cost = cE^\beta$

where *c* is the cost of fishing per unit effort, *E* is the effort applied that year, and $\beta$ is a constant >1. $\beta$ allows the cost of fishing to increase with increasing effort. This allows us to avoid corner solutions in our model.

### Profit

The profit of fishing each year is calculated as follows:

$\pi = pH - cost$

where $p$ is the price of one unit of fish, $H$ is the yearly harvest, and $cost$ is the cost of fishing that year.


## Adapting this model to quota baskets

To determine how we can adapt our model to reveal how a quota basket will affect a fishery, we first must define what a quota basket is. A quota basket limits the total annual harvest of a group of fish. Within this basket, fishers can target and catch any fish in that basket until the quota is hit. We must incorporate both of these dynamics into our model.

### Effort

Fishers can target any species until a quota is hit. The critical question for our model then becomes: where will fishers choose to put their effort under a quota basket? To answer this question, we must provide a way for fishers to "choose" their effort allocation each year.

In the real world, fishers target fish by changing their gear type, time of fishing, etc to give them the best chance of catching a certain type of fish. To simulate this dynamic, we provide fishers with a choice of "technologies" that represent different targeting strategies. Each technology alters the catchability $q$ of each fish species. A technology can catch multiple species at different rates, allowing us to incorporate non-selective technologies such as trawling. This also allows us to incorporate some bycatch with each technology.

How each technology affects a certain species is reflected in a matrix, where the rows represent technologies, the columns represent species, and each value represents the catchability of a species with a certain technology. A matrix for two technologies and two species looks like this:

### *Insert species tech matrix here!!**

Fishers choose the effort applied to each technology. Each technology harvests a different amount of each species. To show how much of each species is caught per year, we must sum the amount of each species caught by each technology. A single technology can be broken down into harvest by species. For example, if we consider a two species fishery, we see that the number of each species harvested by a technology is:

$\begin{aligned}
H_{s_1} = q_{s_1}EX_{s_1} \nonumber \\
H_{s_2} = q_{s_2}EX_{s_2} \nonumber
\end{aligned}$

where subscript $s$ denotes species. The stock and q are dependent on the species harvested, but the effort is applied to the technology and does not change over species. If we consider multiple technologies, the harvest of each species is the sum of the harvest of that species by each technology. For a two technology fishery, we can write the harvest of species 1 as follows:

$H_{s_1} = (q_{s_1, tech_1}E_{tech_1}X_{s_1}) + (q_{s_1, tech_2}E_{tech_2}X_{s_1})$

We can rewrite these equations to include any number of species and technologies, and the harvest for a species $j$ is the sum of the harvest for each technology $i$:

$H_j = \sum_{i=1}^{n Tech} q_{(i,j)}E_{i}X_{j}$

where the catchability $q$ depends on both the species $j$  and the technology$i$, the effort $E$ depends on just the technology$i$, and the stock depends on just the species $j$.

### Maximizing profits

Why would a fisher choose a certain technology over another? We assume that effort will be preferentially allocated to the most profitable technology. We know already that each species of fish fetches a price $p$ in the market. However, our initial profit model assumed the cost of fishing was a function of the species of fish caught. We can instead assign a cost of fishing $c$ to each *technology*. This allows us to calculate the profit $\pi$ of each technology $i$ per year:

$\pi_i = [\sum_{j = 1}^{nSpecies} p_jH_(j,i)] - c_iE_i^\beta$

where the total profit for a given technology is the sum of the revenue from each unit of fish caught by the technology minus the total cost of fishing for that technology. We make an important assumption here:

- Bycatch can still be sold for full price

Note that each unit of fish caught has a downward sloping marginal profit, which will allow our optimum effort allocation to include multiple technologies.

### Optimizing from the fishers perspective

We assume that a fisher will decide to allocate their yearly effort to the combination of efforts that returns the maximum profit each year. Furthermore, we assume that fishers are myopic, only considering the current yearly profit when choosing where to allocate their effort. Our optimization routine can therefore select the combination of efforts that returns the max profit for that year. We can solve our effort equation:

### Insert all the math here!!! ###

### Implementing a quota basket:

Left to their own devices, fishers will choose to allocate their effort to the combination of technologies that returns the most profit each year. Quota baskets group fish by some common trait. These baskets can contain many species within them. 

Many traits introduce unwanted complexity into our model. For example, defining a basket by size requires building a size structured fisheries model to demonstrate the effect of a size basket on a fishery. To reduce unwanted complexity in our model, we intentionally leave our grouping variable undefined. This leaves us with the following assumptions:

- Grouping traits are undefined
- Traits have no effect on any model parameters

We can add an additional assumption: fish species, as defined in our model, are representative of individual traits. So, we can group different species of fish into baskets, and assign a quota to each basket. While many exceptions to this concept exist (eg. each species of fish has small and large fish, and so members of a single species can occupy multiple baskets), this assumption simplifies our model greatly. Plus, some fish are managed in species baskets, like groundfish in California, so this approach can reveal real-world consequences.

Our quota basket can be applied via a constraint to our analytical effort solution to this model. We first must group all the species in our fishery into baskets. Allowable catches within a basket can be controlled in two ways: by either limiting effort for each technology, or by limiting the units of fish within a basket that are harvested each year. If we group a four-species fishery into two baskets:

$\begin{aligned} 
Basket 1 = speciesA + speciesB \nonumber \\ 
Basket 2 = speciesC + speciesD \nonumber 
\end{aligned}$

we can set a biomass limit for each basket as such:

$\begin{aligned} 
H_{basket 1} \leq 500 \nonumber \\ 
H_{basket 2} \leq 300 \nonumber 
\end{aligned}$

and solve for the combination of efforts per technology that maximizes profit subject to the constraint. 





