# write a function to calculate the profit for one technology
profit_tech <- function(tech_index, E){
  
  # apply the third equation in "Our Model" section. Calculate the revenue generated by the 1st species of the chosen technology
  profit_tech_species = species_tech_matrix[tech_index, 1]*E[tech_index]*simul_stock_dynamic[1]*parameter$p[1]
  
  # use a for-loop to generate the revenue for the rest of the species for that tech 
  for(j in 2:species_num){
    x = species_tech_matrix[tech_index, j]*E[tech_index]*simul_stock_dynamic[j]*parameter$p[j]
    profit_tech_species <- cbind(profit_tech_species,x)
  }
  
  # sum by rows to get the revenue generated by that technology across species. Subtract cost from revenue to get profit of that technology
  
  # calculate the cost for each technology
  cost_tech <- C*E
  
  profit_tech = rowSums(profit_tech_species) - cost_tech[tech_index]
  
  return(profit_tech)
}
