# write a function to calculate the present value of the profit generated by each technology each year
pvnb <- function(E){
  profit_year <- rowSums(profit_tech(E))
  pv = NULL
  for(i in 1:year){
    x = rho^(i-1)*profit_year[i]
    pv = append(pv, x)
  }
  return(sum(pv))
}

