# write a function to calculate the present value of the profit generated by each technology each year
pvnb <- function(pro){
  pv = NULL
  for(i in 1:year){
    x = rho^(i-1)*pro$total_profit[i]
    pv = append(pv, x)
  }
  return(sum(pv))
}