---
title: "example_model_run"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(here)
library(quadprog)
```


# DO NOT ALTER THIS DOCUMENT!!!

### Preparing the inputs and outputs for `qb_stock.r`:

For each species, we need:

* r - growth rate
* K - carrying capacity
* X - starting stock
* p - price

For each technology we need:

* Catchability per species
* Cost per unit effort

# Inputs

## Step 1: Input parameters
```{r}
# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.5, K=100, X=50, p=10) 
s2 <- c(s=2, r=0.5, K=100, X=50, p=10) 

# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.05, q2=0.04)
t2 <- c(t=2, q1=0.04, q2=0.05)

# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=1)
c2 <- c(t=2, cost=1)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 1)
b2 <- c(s1 = 0, s2 = 0)

# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceeding stock under constant mortality, so this will have to change to just input constant m.

mortality = 0.1

# Years
years = 30
```

# Step 2: make a list of the inputs
```{r}
# Change these to reflect the number of species and technologies above:
species = list(s1, s2)
tech = list(t1, t2)
cost = list(c1, c2)
baskets = list(b1)
```

# Step 3: Run the function

```{r}
source(here("working_model", "qb_stock.R"))

output <- qb_stock(species, tech, cost, baskets, mortality, years)
```

