---
title: "single_sp_opt"
output: html_document
---

This function should converge at r/2


```{r}


# This finds the optimal steady state harvest point for each individual species, YAAR?



FishOpt_GS<-function(bvec,K,g,p,cost,beta,disc,tol=.1, t_end = 300){
  delta=1/(1+disc)
  #Optim objective function
  Objective<-function(f,b,bvec,K,gar,p,cost,beta,delta,V){
    r<-gar
    bnext = max(min(bvec), b + r*b*(1-b/K) - f)
    bnext = min(max(bvec), bnext) #Make sure we don't go below the minimum biomass
    profit=p*f-cost*f^beta
    Vnext = spline(x=bvec,y=V,xout=bnext)
    negout = -(profit + delta*Vnext$y)
    return(negout) # Negative profits
  }
  #Set up storage vectors and initial loop parameters
  tolcheck=10*tol
  t=0
  Vstar=rep(0,length.out=length(bvec))
  f=rep(1,length.out=length(bvec))
  #While iterate until convergence
  while(t<4|tolcheck>tol){
  t=t+1
  V=Vstar
  pastf=f
  #Loop over states
  for(i in 1:length(bvec)){
  b=bvec[i]
  if(i==1){
  guess=0
  }else{
  guess=f[i-1]
  }
  low=0.00001 ## If you get error in optim finite fn convergence issues, changes this to something positive but REALLY small 0.00001
  high=(b + g*b*(1-b/K)) #Max possible harvest is the available fish plus the growth
  Opt=optim(par=guess,fn=Objective,lower=low,upper=high,method = "L-BFGS-B",b=b,bvec=bvec,gar=g,cost=cost,K=K,p=p,V=V,beta=beta,delta=delta)
  f[i]=Opt$par
  Vstar[i]=-Opt$value
  }
  #Check tolerance in each time period, this is policy function convergence, no check for value function convergence
  tolcheck=sum(abs(f-pastf))
  if(t>t_end){
    print("Exceed Maximum time steps with tolerance remaining:")
    print(tolcheck)
    break
  }
  converge=c(t,tolcheck)
  }
  return(list(Policy=f,Value=Vstar,converge=converge))
}
```


```{r}
##### Define your fishery parameters and run your QB model for all other combinations up to this point ####
## Run the optimization to get policy functions ##
#Each element of these lists correspond to each fishery. For example the first list element in Klist is the carrying capacity for fishery 1 as is the first element in rlist for fishery 1 etc.
bveclist=list(seq(0,200,length.out=50),seq(0,400,length.out=50),seq(0,600,length.out=50))
Klist=list(200,400,600)
rlist=list(0.8,0.5,0.6)
plist=list(50,30,25)
costlist=list(0.1,0.2,0.1)
betalist=list(2,2,2)
disclist=list(0,0,0)
optimal_output=pmap(list(bveclist,Klist,rlist,plist,costlist,betalist,disclist),FishOpt_GS)

optimal_output
```

```{r}
optimal_output

```


```{r}
# Input parameters for this guy:

# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.2, K=100, X=50, p=200) 
s2 <- c(s=2, r=0.3, K=100, X=50, p=200)
s3 <- c(s=3, r=0.4, K=100, X=50, p=200)
s4 <- c(s=4, r=0.5, K=100, X=50, p=200)
s5 <- c(s=5, r=0.6, K=100, X=50, p=200)

# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.05, q2=0.05, q3=0.05, q4=0.05,    q5 = 0.05)
t1 <- c(t=1, q1=0.05, q2=0.05, q3=0.05, q4=0.05,    q5 = 0.05)
t1 <- c(t=1, q1=0.05, q2=0.05, q3=0.05, q4=0.05,    q5 = 0.05)
t1 <- c(t=1, q1=0.05, q2=0.05, q3=0.05, q4=0.05,    q5 = 0.05)
t1 <- c(t=1, q1=0.05, q2=0.05, q3=0.05, q4=0.05,    q5 = 0.05)


# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=10)
c2 <- c(t=2, cost=10)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 1, s3 = 1, s4 = 0, s5 = 0)
b2 <- c(s1 = 0, s2 = 0, s3 = 0, s4 = 1, s5 = 1)

# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceding stock under constant mortality, so this will have to change to just input constant m.

mortality = 0.1

# Years
years = 50
```

# Step 2: make a list of the inputs
```{r}
# Change these to reflect the number of species and technologies above:
species = list(s1, s2, s3, s4, s5)
tech = list(t1, t2, t3, t4, t5)
cost = list(c1, c2)
baskets = list(b1, b2)
```

```{r}
sp_df <- as.data.frame(do.call(rbind, species))
tech_df <- as.data.frame(do.call(rbind, tech))
cost_df <- as.data.frame(do.call(rbind, cost))
baskets_df <- as.data.frame(do.call(rbind, baskets))
```


```{r}
bveclist=list(seq(0.1,sp_df$K[1],length.out=50), seq(0.1,sp_df$K[2],length.out=50), seq(0.1, sp_df$K[3], length.out = 50), seq(0.1,sp_df$K[4],length.out=50), seq(0.1,sp_df$K[5],length.out=50))

Klist=as.list(sp_df$K)
rlist=as.list(sp_df$r)
plist=as.list(sp_df$p)
costlist=list(10, 10, 10, 10, 10)  
betalist=list(2,2,2,2,2)
disclist=list(0,0,0,0,0)
optimal_output=pmap(list(bveclist,Klist,rlist,plist,costlist,betalist,disclist),FishOpt_GS)

optimal_output


run300 <- FishOpt_GS(seq(0, 100, length.out = 50), 100, 0.8, p = 200, c = 10, beta = 2, disc = 0, tol = 0.1, t_end = 300)

run305 <- FishOpt_GS(seq(0, 100, length.out = 50), 100, 0.2, p = 200, c = 10, beta = 2, disc = 0, t_end = 305)

run300
run305

run20

run20=pmap(list(bveclist,Klist,rlist,plist,costlist,betalist,disclist),FishOpt_GS)
```




