---
title: "YearlyLoop"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(quadprog)
```


### Preparing the inputs and outputs for quadprog:

Goals:

Only input species parameters ONCE!!!
Only input gear parameters ONCE!!!


For each species, we need:

* r - growth rate
* K - carrying capacity
* X - starting stock
* p - price

For each technology we need:

* Catchability per species
* Cost per unit effort

# Inputs


## Step 1: Input parameters
```{r}
# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.5, K=100, X=0.5, p=200)
s2 <- c(s=2, r=0.5, K=100, X=0.5, p=200)


# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.05, q2=0.04)
t2 <- c(t=2, q1=0.04, q2=0.05)

# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=1)
c2 <- c(t=2, cost=1)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 1)

# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceeding stock under constant mortality, so this will have to change to just input constant m.

mortality = 0.1

# Years
years = 2
```

# Step 2: make a list of the inputs
```{r}
species = list(s1, s2)
tech = list(t1, t2)
cost = list(c1, c2)
baskets = list(b1)
```

```{r}
qb_stock <- function(species, tech, cost, baskets, mortality, years){
  
  # Make useful data frames of each of our lists: this allows any number to be added.
  sp_df <- as.data.frame(do.call(rbind, species))
  tech_df <- as.data.frame(do.call(rbind, tech))
  cost_df <- as.data.frame(do.call(rbind, cost))
  baskets_df <- as.data.frame(do.call(rbind, baskets))
  
  # Calculate number of tech and species
  ntech <- nrow(tech_df)
  nspecies <- nrow(sp_df)
  
  # Add starting stock values.
  stock_df <- data.frame(t(sp_df$X))
  
  # Make a few full data frames we can fill later
  h_df <- data.frame(matrix(ncol = nspecies))
  e_df <- data.frame(matrix(ncol = ntech))
  
  #WWWW
  # We still probably want to calculate harvest per species AND technology...
  #WWWW
  
  
  ### --------
  ### Unchanging Parameters
  ### --------
  
  # D is the cost matrix, where the diagonal values are the cost of each tech:
  D <- matrix(0, nrow = ntech, ncol = ntech)
  diag(D) <- 2*cost_df$cost
  
  # Z is the the tech matrix
  Z <- as.matrix(tech_df[,-1])
  
  # P is the price matrix
  P <- sp_df$p
  
  # M is whether a species is contained in a basket:
  M <- as.matrix(baskets_df)
    
  ### --------
  ### Changing Parameters
  ### --------
  
  for (i in 1:years){
    ### ------
    ### Calculate effort per year
    ### ------
    E <- NULL
    # B, where the diagonal corresponds to stock sizes (X) for each species
    B <- matrix(0, nrow = nspecies, ncol = nspecies)
    diag(B) <- as.numeric(tail(stock_df,1)) ### Stock goes here...
    # d combines the P,B,and Z vectors
    d <- t(t(P)%*%B%*%Z)
    # A is the transpose matrix that defines which basket each species is in:
    A <- -1*M%*%B%*%Z
    t_A <- t(A)
    # We need to calculate the basket caps based on the initial BASKET size(not stock size!):
    viz_stock <- rowSums(tail(stock_df,1)) ### And here...
    #b <- -10
    b <- -viz_stock * mortality
    # Find optimal efforts
    E <- solve.QP(D,d,t_A,b, meq=0)$solution # Vector where the position is the effort per tech.
    
    ### ------
    ### Calculate harvest for each species for the year
    ### ------
    # Repeat E for each species, so we have effort per tech per species:
    h <- c(B%*%Z%*%E) # Position corresponds to the species:
    # Calculate stock growth with X(t+1) = Xt + Xt*r*(1-Xt/K) - h
    stock_next <- tail(stock_df,1) + sp_df$r*tail(stock_df,1)*(1-tail(stock_df,1)/sp_df$K) - h
    stock_df <- rbind(stock_df, stock_next)
    
    h_df <- rbind(h_df, h)
    e_df <- rbind(e_df, E)
  }
  
  rownames(stock_df) <- NULL
  colnames(stock_df) <- sp_df$s
  return(list(stock = stock_df, harvest = h_df, effort = e_df))
}

test <- qb_stock(species, tech, cost, baskets, mortality, years)

test$effort
test$harvest
test$stock
```




