---
title: "Array problem"
author: "Mauricio Collado"
date: "1/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Packages
library(tidyverse)
library(Matrix)
library(kableExtra)
library(ggplot2)
#library(plotly)
#library(lpSolve)
#library(lpSolveAPI)
library(here)
library(quadprog)
```

```{r}
# read files
# We read the file
q_coefficient <- read_csv(here::here("Quadratic prog", "data4",
                                    "q_tech.csv")) # n tech s species

species_data <- read_csv(here::here("Quadratic prog", "data4",
                                    "species_data.csv")) # s species

species_group <- read_csv(here::here("Quadratic prog", "data4",
                                    "species_group.csv")) # m qb

effort_cost <- read_csv(here::here("Quadratic prog", "data4",
                                    "effort_costs.csv")) # n efforts

quota_cap <- read_csv(here::here("Quadratic prog", "data4",
                                    "quota_cap.csv")) # m qb

test_e <- read_csv(here::here("Quadratic prog","data4",
                                    "test_e.csv")) # m qb
```

```{r}
# First, set seed to ensure we have the same result 
set.seed(666)


# set the number of species and technologies we want to study
s <- as.numeric(nrow(species_data)) #species
n <- as.numeric(nrow(effort_cost)) #tecnologies
m <- as.numeric(nrow(quota_cap)) #quota baskets

```


```{r}
# D (costs)

# set cost for each tech
Cost <- effort_cost[['Cost']]

#Cost <- c(1,1)

Cost2 <- 2*Cost

# nxn 
D <- matrix(0, nrow=n,ncol=n)
diag(D) <- Cost2

```

```{r}
# d

#prices (sx1)
p <- species_data[['price_x']]

#p <- c(200,200)

# stock in period 0
X_0 <- species_data[['stock_x']]

# X_0 <- c(0.5,0.5)

# stock matrix (sxs)
B <- matrix(0, nrow=s,ncol=s)
diag(B) <- X_0

# catchability matrix (sxn)
coefficient <- data.matrix(q_coefficient)
  
#c(0.05,0.04,
# 0.04,0.05)

Z <- matrix(coefficient, nrow=s,ncol=n)

#d t(sx1)(sxs)(sxn)=(1xn)
t_d <- t(p)%*%B%*%Z

#nx1
d <- t(t_d)

```

```{r}
# quota basket matrix (mxs)
coefficient_qb <- data.matrix(species_group)

# coefficient_qb <- c(1,1)

W <- matrix(coefficient_qb, nrow=m,ncol=s) # CORRECTION it was name D in the document, and D is defined as cost. I renamed it as W.

#A(mxs)(sxs)(sxn)=(mxs)
A <- -1*W%*%B%*%Z
t_A <- t(A)
```

```{r}
#quota basket caps (mx1)
b_0 <- quota_cap[['cap']]

#b_0 <- c(10)
b <- -1*b_0

```

```{r}
# quadprog

# solve.QP(Dmat, dvec, Amat, bvec, meq=0, factorized=FALSE)
# (1xn).(nxn)(nx1)-(1xn)(nx1) subject to :(mxn)(nx1) = (mx1) ≥ (mx1)
# D: symmetric matrix with the quadratic component (Dmat)
# d: linear term (dvec)
# A: matrix with linear constraints (Amat)
# b: constraints (bvec)

# (1xn).(nxn)(nx1)-(1xn)(nx1) subject to :(mxn)(nx1) = (mx1) ≥ (mx1)
 
quad_run <- solve.QP(D,d,t_A,b, meq=0)
quad_solution <- quad_run$solution

quad_run
```


```{r}
# revenue

# d*E
A_rev <- t_d%*%quad_solution

#cost
A_cos <- (1/2)*t(quad_solution)%*%D%*%quad_solution

A_profit <- A_rev - A_cos

```



```{r}

test_profit_fx <- function(years){
  profit<- vector(length = years)
  E <- vector(length = years)
  revenue <- vector(length = years)
  cost <- vector(length = years)
  solution <- vector(length = years)
  # And write a stock size equation
  for(y in 1:years){
  # profit
  E[y] <- test_e$E_theory[y]
  quad_solution2 <- c(E[y],E[y])
  solution[y] <- quad_solution2
  # quad_solution3 <- c(E[y],E[y])
  cost[y]=(1/2)*t(quad_solution2)%*%D%*%quad_solution2
  revenue[y] = t_d%*%quad_solution2
  profit[y]=revenue[y]-cost[y]
  }
  data.frame(year = seq(1, years, by = 1), 
             E = E, 
             solution=solution,
             revenue=revenue,
             cost=cost,
             profit= profit)
  }
  
 
```

```{r}

test_up <- test_profit_fx(years=100) 

test_up_filter <- test_up %>% 
  filter(profit>0)

ggplot(data=test_up_filter, aes(x=E, y=profit)) +
  geom_line() +
  labs(title="Quota basket: 2 j, 2 i, 1 k (1,2)")

```

```{r}
test_profit_fx1 <- function(years){
  profit<- vector(length = years)
  E <- vector(length = years)
  revenue <- vector(length = years)
  cost <- vector(length = years)
  # And write a stock size equation
  for(y in 1:years){
  # profit
  E[y] <- test_e$E_theory[y]
  quad_solution3 <- c(E[y],E[y],E[y]) # efforts
  # quad_solution3 <- c(E[y],E[y])
  cost[y]=(1/2)*t(quad_solution3)%*%D%*%quad_solution3
  revenue[y] = t_d%*%quad_solution3
  profit[y]=revenue[y]-cost[y]
  }
  data.frame(year = seq(1, years, by = 1), 
             E = E, 
             revenue=revenue,
             cost=cost,
             profit= profit)
}

test_up <- test_profit_fx1(years=100) 

test_up_filter <- test_up %>% 
  filter(profit>0)

ggplot(data=test_up_filter, aes(x=E, y=profit)) +
  geom_line() +
  labs(title="Quota basket: 3 j, 3 i, 2 k (1,2;3)")
  
```

```{r}
test_profit_fx2 <- function(years){
  profit<- vector(length = years)
  E1 <- vector(length = years)
  E2 <- vector(length = years)
  revenue <- vector(length = years)
  cost <- vector(length = years)
  # And write a stock size equation
  for(y in 1:years){
  # profit
  E1[y] <- test_e$E_theory1[y]
  E2[y] <- test_e$E_theory2[y]
  quad_solution3 <- c(E1[y],E1[y],E1[y],E1[y],E2[y]) # efforts
  # quad_solution3 <- c(E[y],E[y])
  cost[y]=(1/2)*t(quad_solution3)%*%D%*%quad_solution3
  revenue[y] = t_d%*%quad_solution3
  profit[y]=revenue[y]-cost[y]
  }
  data.frame(year = seq(1, years, by = 1), 
             E1 = E1, 
             E2 = E2, 
             revenue=revenue,
             cost=cost,
             profit= profit)
}

test_up <- test_profit_fx2(years=133) 

test_up_filter <- test_up %>% 
  filter(profit>0) %>% 
  arrange(-profit) %>% 
  head(20)

```

```{r}
vec_E1 <-seq(0.5, 15, by = 0.5)
vec_E2 <-seq(0.5, 15, by = 0.5)
vec_E3 <-seq(0.5, 15, by = 0.5)
vec_E4 <-seq(0.5, 15, by = 0.5)

list_vector_E <- list(vec_E1,vec_E2,vec_E3,vec_E4)

test_e4 <- expand.grid(list_vector_E)
```


```{r}

test_profit_fx3 <- function(years){
  profit<- vector(length = years)
  E1 <- vector(length = years)
  E2 <- vector(length = years)
  E3 <- vector(length = years)
  E4 <- vector(length = years)
  revenue <- vector(length = years)
  cost <- vector(length = years)
  # And write a stock size equation
  for(y in 1:years){
  # profit
  E1[y] <- test_e4$Var1[y]
  E2[y] <- test_e4$Var2[y]
  E3[y] <- test_e4$Var3[y]
  E4[y] <- test_e4$Var4[y]
  quad_solution3 <- c(E1[y],E2[y],E3[y],E4[y]) # efforts
  # quad_solution3 <- c(E[y],E[y])
  cost[y]=(1/2)*t(quad_solution3)%*%D%*%quad_solution3
  revenue[y] = t_d%*%quad_solution3
  profit[y]=revenue[y]-cost[y]
  }
  data.frame(year = seq(1, years, by = 1), 
             E1 = E1, 
             E2 = E2, 
             E3 = E3,
             E4 = E4, 
             revenue=revenue,
             cost=cost,
             profit= profit)
}

test_up <- test_profit_fx3(years=810000) 

test_up_filter <- test_up %>% 
  filter(profit>0) %>% 
  arrange(-profit) %>% 
  head(20)

```

```{r}

# CLEAR ENVIRONMENT
rm(list = ls())
```



