---
title: "YearlyLoop"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(ggplot2)
library(cowplot)
library(quadprog)

```


### Preparing the inputs and outputs for quadprog:

Goals:

Only input species parameters ONCE!!!
Only input gear parameters ONCE!!!


For each species, we need:

* r - growth rate
* K - carrying capacity
* X - starting stock
* p - price

For each technology we need:

* Catchability per species
* Cost per unit effort

# Inputs


## Step 1: Input parameters
```{r}

# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.3, K=100, X=50, p=10) 
s2 <- c(s=2, r=0.4, K=100, X=50, p=10)
s3 <- c(s=3, r=0.5, K=100, X=50, p=10)
s4 <- c(s=4, r=0.6, K=100, X=50, p=10)
s5 <- c(s=5, r=0.7, K=100, X=50, p=10)

# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.05, q2=0.03, q3=0.03, q4=0,    q5 = 0)
t2 <- c(t=2, q1=0,    q2=0,    q3=0.03, q4=0.03, q5 = 0.05)


# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=1)
c2 <- c(t=2, cost=1)

# Baskets: binary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 1, s3 = 1, s4 = 0, s5 = 0)
b2 <- c(s1 = 0, s2 = 0, s3 = 0, s4 = 1, s5 = 1)

# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceding stock under constant mortality, so this will have to change to just input constant m.

mortality = 0.1

# Years
years = 50
```


# Step 2: make a list of the inputs
```{r}
species = list(s1, s2, s3, s4, s5)
tech = list(t1, t2)
cost = list(c1, c2)
baskets = list(b1, b2)
```

```{r}
qb_stock <- function(species, tech, cost, baskets, mortality, years){
  
  # Make useful data frames of each of our lists: this allows any number to be added.
  sp_df <- as.data.frame(do.call(rbind, species))
  tech_df <- as.data.frame(do.call(rbind, tech))
  cost_df <- as.data.frame(do.call(rbind, cost))
  baskets_df <- as.data.frame(do.call(rbind, baskets))
  
  # Calculate number of tech and species
  ntech <- nrow(tech_df)
  nspecies <- nrow(sp_df)
  
  # Add starting stock values.
  stock_df <- data.frame(t(sp_df$X))
  
  # Make a few full data frames we can fill later
  h_df <- data.frame(matrix(ncol = nspecies))
  e_df <- data.frame(matrix(ncol = ntech))
  
  ## Profits:
  pft_df <- data.frame(matrix(ncol = ntech))
  pft_sp_df <- data.frame(matrix(ncol = nspecies))
  
  #WWWW
  # We still probably want to calculate harvest per species AND technology...
  #WWWW
  
  
  ### --------
  ### Unchanging Parameters
  ### --------
  
  # D is the cost matrix, where the diagonal values are the cost of each tech:
  D <- matrix(0, nrow = ntech, ncol = ntech)
    diag(D) <- 2*cost_df$cost
  
  # Z is the the tech matrix
  Z <- t(as.matrix(tech_df[,-1]))
  
  # P is the price matrix
  P <- as.matrix(sp_df$p)
  
  # M is whether a species is contained in a basket:
  M <- as.matrix(baskets_df)
  
  # We build a diagonal matrix (nxn) for the second constraint
  N <- matrix(0, nrow=ntech,ncol=ntech)
    diag(N) <- 1
    
  ### --------
  ### Changing Parameters
  ### --------
  
  for (i in 1:years){
    ### ------
    ### Calculate effort per year
    ### ------
    E <- NULL
    # B, where the diagonal corresponds to stock sizes (X) for each species
    B <- matrix(0, nrow = nspecies, ncol = nspecies)
      diag(B) <- as.numeric(tail(stock_df,1)) ### Stock goes here...
    # d combines the P,B,and Z matrices yielding the per tech revenue (1xtech)
    # (1xspecies)x(speciesxspecies)x(speciesxtech)
    d <- t(t(P)%*%B%*%Z)
    # A is the transpose matrix that defines which basket each species is in:
    A <- -1*M%*%B%*%Z
      # Add the second constraint N:
      A <- rbind(A, N)
      # Take the transpose for solve.QP:
      t_A <- t(A)
    # We need to calculate the basket caps based on the initial BASKET size(not stock size!):
    viz_stock <- rowSums(tail(stock_df,1)) ### And here...
    # Make the first constraint based on mortality:
    b <- -M%*%(mortality*t(as.matrix(tail(stock_df, 1))))
      # Make a second constraint so they're all greater than zero:
      b2 <- matrix(0, nrow=ntech, ncol=1)
      # Bind them together
      b <- rbind(b, b2)
    # Find optimal efforts
    E <- solve.QP(D,d,t_A,b, meq=0)$solution # Vector where the position is the effort per tech.
    
    ### ------
    ### Calculate harvest for each species for the year
    ### ------
    # Repeat E for each species, so we have effort per tech per species:
    h <- c(B%*%Z%*%E) # Position corresponds to the species:
    # Calculate stock growth with X(t+1) = Xt + Xt*r*(1-Xt/K) - h
    stock_next <- tail(stock_df,1) + sp_df$r*tail(stock_df,1)*(1-tail(stock_df,1)/sp_df$K) - h
    stock_df <- rbind(stock_df, stock_next)
    
    ### Calculate profit for each technology for the year
    ### -----

    # (1xtech)*(techx1)
    Rev <- as.data.frame(t(d)*E)

    # .5 * (1xtech) * (techxtech) x (techx1)
    Costz <- as.data.frame((1/2)*t(E)%*%D*E)

    pft <- as.data.frame(Rev - Costz)
    names(pft) <- names(pft_df)

    ### Profit per species
    ### -----

    # (1xtech)*(techxspecies) = (1xspecies)
    # profit per tech x catchability

    # pft_sp <- pft*Z
    
    h_df <- rbind(h_df, h)
    e_df <- rbind(e_df, E)
    pft_df <- rbind(pft_df, pft)
    # pft_sp_df <- rbind(pft_sp_df, pft_sp)

  }
  
  rownames(stock_df) <- NULL
  colnames(stock_df) <- sp_df$s
  return(list(stock = stock_df, harvest = h_df, effort = e_df, profit = pft_df))
              
              # profit_species = pft_sp_df))
}

test <- qb_stock(species, tech, cost, baskets, mortality, years)

test$effort
test$harvest
test$stock
test$profit
# test$profit_species Does not work

test <- qb_stock(species, tech, cost, baskets, mortality, years)

```

```{r}
# we put results into a dataframe
results <- as.data.frame(test) %>% 
  mutate(stock_total=stock.1+stock.2, # we sum stocks...
         profit_total=profit.X1+profit.X2) #we sum profits...

# graphs of effort and harvest
effort_x1 <- ggplot(results)+
  geom_line(aes(x=years,y=effort.X1), color="red")+
  labs(title="Effort for tech 1")

effort_x2 <- ggplot(results)+
  geom_line(aes(x=years,y=effort.X2), color="blue")+
  labs(title="Effort for tech 2")

harvest_x1 <- ggplot(results)+
  geom_line(aes(x=years,y=harvest.X1), color="darkgreen")+
  labs(title="Harvest of species 1")

harvest_x2 <- ggplot(results)+
  geom_line(aes(x=years,y=harvest.X2), color="purple")+
  labs(title="Harvest of species 2")

plot_grid(effort_x1, harvest_x1, 
          effort_x2, harvest_x2, 
          labels = c("A1", "A2", "B1", "B2"),
          ncol = 2, nrow = 2)

# graphs of biomass
biomass_x1 <- ggplot(results)+
  geom_line(aes(x=years,y=stock.1), color="red")+
  labs(title="Stock species 1")

biomass_x2 <- ggplot(results)+
  geom_line(aes(x=years,y=stock.2), color="blue")+
  labs(title="Stock species 2")

biomass_x <- ggplot(results)+
  geom_line(aes(x=years,y=stock_total), color="darkgreen")+
  labs(title="Stock species total")

plot_grid(biomass_x, biomass_x1, biomass_x2, 
          labels = c("A", "B", "C"),
          ncol = 2, nrow = 2)

# graphs for profits

profits_e1 <- ggplot(results)+
  geom_line(aes(x=years,y=profit.X1), color="red")+
  labs(title="Profits from tech 1")

profits_e2 <- ggplot(results)+
  geom_line(aes(x=years,y=profit.X2), color="blue")+
  labs(title="Profits from tech 2")

profits_total <- ggplot(results)+
  geom_line(aes(x=years,y=profit_total), color="darkgreen")+
  labs(title="Profits total")

plot_grid(profits_total, profits_e1, profits_e2, 
          labels = c("A", "B", "C"),
          ncol = 2, nrow = 2)
```



