---
title: "Results_all_constant_but_price"
author: "Kat Leigh"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(ggplot2)
library(here)
library(quadprog)
library(scales)
library(DT)
```

```{r}

# read in data

output_b_20 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p20.csv")
NPV_20 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p20.csv")

output_b_1 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p1.csv")
NPV_1 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p1.csv")

output_b_10 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p10.csv")
NPV_10 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p10.csv")

output_b_30 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p30.csv")
NPV_30 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p30.csv")

output_b_40 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p40.csv")
NPV_40 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p40.csv")

output_b_50 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p50.csv")
NPV_50 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p50.csv")

output_b_60 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p60.csv")
NPV_60 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p60.csv")

output_b_70 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p70.csv")
NPV_70 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p70.csv")

output_b_80 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p80.csv")
NPV_80 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p80.csv")

output_b_90 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p90.csv")
NPV_90 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p90.csv")

output_b_100 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreoutput_def_p100.csv")
NPV_100 <- read_csv("C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/model run result files/price and cost exploreNPV_def_p100.csv")

NPVs <- rbind(NPV_1, NPV_10, NPV_20, NPV_30, NPV_40, NPV_50, NPV_60, NPV_70, NPV_80, NPV_90, NPV_100)

```
# Visualize Results

```{r}
# profits

pfts_1 <- output_b_1 %>% 
  select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "1")

pfts_10 <- output_b_10 %>% 
  select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "10")

pfts_20 <- output_b_20%>% 
  select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "20")

pfts_30 <- output_b_30%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "30")

pfts_40 <- output_b_40%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "40")

pfts_50 <- output_b_50%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "50")

pfts_60 <- output_b_60%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "60")

pfts_70 <- output_b_70%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "70")

pfts_80 <- output_b_80%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "80")

pfts_90 <- output_b_90%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "90")

pfts_100 <- output_b_100%>%    select(profit_per_t.t_1:profit_per_t.t_2.3) %>% 
  mutate(run = "100")

combo_pfts <- rbind(pfts_1, pfts_10, pfts_20, pfts_30, pfts_40, pfts_50, pfts_60, pfts_70, pfts_80, pfts_90, pfts_100)

tots <- combo_pfts$profit_per_t.t_1 + combo_pfts$profit_per_t.t_2 + combo_pfts$profit_per_t.t_2.1 + combo_pfts$profit_per_t.t_2.2 + combo_pfts$profit_per_t.t_2.3

combo_pfts_f <- cbind(combo_pfts, tots)

```

```{r}
combo_pfts_f$run <- factor(combo_pfts_f$run, levels = c("1", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"))

pft_g <- ggplot()+
  geom_smooth(data = combo_pfts_f, aes(y=tots/1000, x=rep(0:30,11), color = as.factor(run)), se = FALSE)+ theme_minimal()+
  labs(title= str_wrap("Predicted annual profits for a multi-species fishery with uniform prices managed by 2 quota baskets", 80),
       caption= str_wrap("Results of a 2 quota basket model for 5 species and 5 technologies parameterized such that species are identical in the following parameters: initial stock size = 50, fishing costs = 1, carrying capacities = 100, coefficient for quota basket limits = 0.2. The coefficient for quota basket limit defines the total combined biomass that can be extracted per year as a proportion of the total available biomass for that year. Species differ in terms of: growth rates = 0.15, 0.2, 0.2, 0.3, 0.4 (respective to each species, 1-5), catchabilities per technology = all 0.01 except for t1 catches species1 at 0.04, t2 catches species2 at 0.04, t3 catches species3 at 0.04, t4 catches species4 at 0.04, and t5 catches species5 at 0.04. Model was run for 11 different uniform price levels (see legend).", 100),
         x= "Number of Years",
         y= "Fishery-wide Annual Profits (thousands)",
       color= "Price Level")+
  scale_color_discrete(labels = c(dollar(as.numeric(levels(combo_pfts_f$run)))))+
  scale_y_continuous(labels=dollar_format(prefix="$"))+
  theme(plot.caption = element_text(hjust = 0))

```

```{r}
# stock

stock_1 <- output_b_1 %>% 
  select(stock.s_1:stock.s_5) %>% 
  mutate(run = "1")

stock_10 <- output_b_10 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "10")

stock_20 <- output_b_20 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "20")

stock_30 <- output_b_30 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "30")

stock_40 <- output_b_40 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "40")

stock_50 <- output_b_50 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "50")

stock_60 <- output_b_60 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "60")

stock_70 <- output_b_70 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "70")

stock_80 <- output_b_80 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "80")

stock_90 <- output_b_90 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "90")

stock_100 <- output_b_100 %>%    select(stock.s_1:stock.s_5) %>% 
  mutate(run = "100")

combo_stock <- rbind(stock_1, stock_10, stock_20, stock_30, stock_40, stock_50, stock_60, stock_70, stock_80, stock_90, stock_100)

tots <- combo_stock$stock.s_1 + combo_stock$stock.s_2 + combo_stock$stock.s_3 + combo_stock$stock.s_4 + combo_stock$stock.s_5

combo_stock_f <- cbind(combo_stock, tots)

```

```{r}
combo_stock_f$run <- factor(combo_stock_f$run, levels = c("1", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"))

stock_g <- ggplot()+
  geom_smooth(data = combo_stock_f, aes(y=tots, x=rep(0:30,11), color = as.factor(run)), se = FALSE)+ theme_minimal()+
  labs(title= str_wrap("Predicted annual stock levels for a multi-species fishery with uniform prices managed by 2 quota baskets", 80),
       caption= str_wrap("Results of a 2 quota basket model for 5 species and 5 technologies parameterized such that species are identical in the following parameters: initial stock size = 50, fishing costs = 1, carrying capacities = 100, coefficient for quota basket limits = 0.2. The coefficient for quota basket limit defines the total combined biomass that can be extracted per year as a proportion of the total available biomass for that year. Species differ in terms of: growth rates = 0.15, 0.2, 0.2, 0.3, 0.4 (respective to each species, 1-5), catchabilities per technology = all 0.01 except for t1 catches species1 at 0.04, t2 catches species2 at 0.04, t3 catches species3 at 0.04, t4 catches species4 at 0.04, and t5 catches species5 at 0.04. Model was run for 11 different uniform price levels (see legend).", 100),
         x= "Number of Years",
         y= "Fishery-wide Annual Stock Level (tons)",
       color= "Price Level")+
  scale_color_discrete(labels = c(dollar(unique(as.numeric(combo_pfts_f$run)))))+
  theme(plot.caption = element_text(hjust = 0))

```
compare levels of each stock

```{r}

longer_stock_f <- combo_stock_f %>% 
  pivot_longer(cols = c(stock.s_1:stock.s_5, tots), names_to = "Species", values_to = "Stock_Level")

longer_stock_f$facet <- factor(longer_stock_f$run, levels = c(1, seq(10,100,10)))

longer_stock_f <- longer_stock_f %>% 
  mutate(sign = '$') %>% 
  transform(newcol=paste(sign, facet, sep="")) %>% 
  select(-sign)

longer_stock_f$Species <- factor(longer_stock_f$Species, levels = c("stock.s_1", 'stock.s_2', 'stock.s_3', 'stock.s_4', 'stock.s_5', 'tots'), 
                  labels = c("Species 1", "Species 2", "Species 3", 'Species 4', 'Species 5', 'Fishery Total'))

longer_stock_f$facet <- factor(longer_stock_f$facet, levels = c(1, seq(10,100,10)),
                               labels = unique(longer_stock_f$newcol))

stock_comp_g <- ggplot()+
  geom_smooth(data = filter(longer_stock_f, Species != "Fishery Total"), aes(y=Stock_Level, x=rep(0:30,55), color = Species), se = FALSE)+ theme_minimal()+ facet_wrap(~ facet)+
  labs(title= str_wrap("Predicted annual stock levels for a multi-species fishery with uniform prices managed by 2 quota baskets", 80),
       caption= str_wrap("Results of a 2 quota basket model for 5 species and 5 technologies parameterized such that species are identical in the following parameters: initial stock size = 50, fishing costs = 1, carrying capacities = 100, coefficient for quota basket limits = 0.2. The coefficient for quota basket limit defines the total combined biomass that can be extracted per year as a proportion of the total available biomass for that year. Species differ in terms of: growth rates = 0.15, 0.2, 0.2, 0.3, 0.4 (respective to each species, 1-5), catchabilities per technology = all 0.01 except for t1 catches species1 at 0.04, t2 catches species2 at 0.04, t3 catches species3 at 0.04, t4 catches species4 at 0.04, and t5 catches species5 at 0.04. Model was run for 11 different uniform price levels (see legend).", 100),
         x= "Number of Years",
         y= "Annual Stock Level (tons)",
       color= "Species")+
  theme(plot.caption = element_text(hjust = 0))+
  scale_color_viridis_d()

```


```{r}
# analyze a bit...

compare_pft_prices <- combo_pfts_f %>% 
  group_by(as.factor(run)) %>% 
  summarise(sum = sum(tots, na.rm = TRUE),
            average = mean(tots, na.rm = TRUE)) %>% 
  arrange(-average)

compare_stock_prices <- combo_stock_f %>% 
  group_by(as.factor(run)) %>% 
  summarise(sum = sum(tots, na.rm = TRUE),
            average = mean(tots, na.rm = TRUE)) %>% 
  arrange(-average)

level_30 <- stock_20$stock.s_1[31] + stock_20$stock.s_2[31] + stock_20$stock.s_3[31] + stock_20$stock.s_4[31] + stock_20$stock.s_5[31]

```

Export results

```{r}
# data

# pft

path_store <- "C:/Users/kll86/OneDrive/Documents/UCSB/quotabasket_model/working_model/price and cost explore/"
  csvname <- "pft_data_p_uniform_defaults.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(combo_pfts_f),csvfile, row.names=FALSE, sep=",")
  
  csvname <- "pft_comparison_p_uniform_defaults.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(compare_pft_prices),csvfile, row.names=FALSE, sep=",")

# stock

  csvname <- "stock_data_p_uniform_defaults.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(combo_stock_f),csvfile, row.names=FALSE, sep=",")

  csvname <- "stock_comparison_p_uniform_defaults.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(compare_stock_prices),csvfile, row.names=FALSE, sep=",")
  
  csvname <- "stock_level30_p_uniform_defaults.csv"
  csvfile <- paste(path_store, csvname, sep="")
  write.table(na.omit(level_30),csvfile, row.names=FALSE, sep=",")
  
# graphs

# pft
ggsave(
  filename = 'pft_data_p_uniform_defaults.jpg',
  plot = pft_g,
  path = path_store)

# stock
ggsave(
  filename = 'stock_data_p_uniform_defaults.jpg',
  plot = stock_g,
  path = path_store)

ggsave(
  filename = 'stock_comp_p_uniform_defaults.jpg',
  plot = stock_comp_g,
  path = path_store)

```

