---
title: "5s_3t_2b"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(here)
library(quadprog)
```

### Preparing the inputs and outputs for `qb_stock.r`:

For each species, we need:

* r - growth rate
* K - carrying capacity
* X - starting stock
* p - price

For each technology we need:

* Catchability per species
* Cost per unit effort

# Inputs

## Step 1: Input parameters
```{r}
# Species:
# s = species, r, K, X, p

s1 <- c(s=1, r=0.3, K=100, X=50, p=10) 
s2 <- c(s=2, r=0.4, K=100, X=50, p=10)
s3 <- c(s=3, r=0.5, K=100, X=50, p=10)
s4 <- c(s=4, r=0.6, K=100, X=50, p=10)
s5 <- c(s=5, r=0.7, K=100, X=50, p=10)

# t = tech, q1 = catchability species 1, q2 = catchability species 2...

t1 <- c(t=1, q1=0.05, q2=0.03, q3=0.03, q4=0,    q5 = 0)
t2 <- c(t=2, q1=0,    q2=0,    q3=0.03, q4=0.03, q5 = 0.05)


# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=1)
c2 <- c(t=2, cost=1)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 1, s3 = 1, s4 = 1, s5 = 1)


# Quotas: position = basket, number is the harvest limit.
# We want this to be 0.1 of the preceding stock under constant mortality, so this will have to change to just input constant m.

mortality = 0.1

# Years
years = 50
```

# Step 2: make a list of the inputs
```{r}
# Change these to reflect the number of species and technologies above:
species = list(s1, s2, s3, s4, s5)
tech = list(t1, t2)
cost = list(c1, c2)
baskets = list(b1)
```

# Step 3: Run the function

```{r}
source(here("working_model", "qb_stock.R"))

# Get max mortality
qb_max_p <- function(species, tech, cost, baskets, mortality, years, discount = 0.05){
  mort <- seq(0.1, 0.9, by = 0.01)
  p_out <- data_frame(m = 0, prof = 0)
  for(i in mort){
    out <- qb_stock(species, tech, cost, baskets, mortality = i, years)
    total_prof <- sum(colSums(out$profit_per_t, na.rm = TRUE))
    p_out <- rbind(p_out, c(i, total_prof))
  }
  return(p_out)
}

# Max mortality is 0.22

max_m <- qb_max_p(species, tech, cost, baskets, mortality, years, discount = 0.05)
row_number <- which.max(max_m$prof)
max_mort <- max_m$m[row_number]

output <- qb_stock(species, tech, cost, baskets, mortality = max_mort, years)
```


# ggplot wrapper:
```{r}


```

